app.py
utils/init_app.py

Made a better way to map the pathname to the filename.  Accommodates pathnames that differ from the filename and path templates.

fixed fullscreen btn bug

---

examples/plotly-express.py
pages/home-search.py
utils/code_and_show.py
utils/feature_app.py
utils/search.py

Added padding to app gallery content
Added the ability to do "and" or "or" for words in searches.  The default is currently "and" for everything.
Added a feature app component

 app update

---

pages/plot-data-from-csv.py
pages/plotly-express.py

[@Coding-with-Adam take a look at this is this alright or do I need to change or add something please let me know](https://github.com/AnnMarieW/dash-app-gallery/pull/52)

adding description and notes to plot-data-from-csv.py

---

pages/poisson-distribution.py
pages/population-density.py
pages/roc-and-pr-curves.py

I didn't know the author of the Poisson distribution app. (It wasn't me who contributed that app. ), 
need info about the population-density app's author ( I think it's contributed by plotly but I am not sure ).

adding notes to 3 more apps

---

examples/scatter-matrix-app.py

Adding my apps one at a time, as Adam recommended :)

adding-scatter-matrix-app

---

app.py

re-activated the app refresh when transitioning form fullscreen app mode

activate fullscreen refresh

---

app.py
examples/pattern-match.py

Refactored in an attempt to make it easier to understand.
If it's still too complex, it could be made into two apps:
1 Simplify this app so it has no delete button on each card.
2 Add a minimal app like [this one from the docs](https://dash.plotly.com/pattern-matching-callbacks#simple-example-with-match), but with a delete button for each filter

refactor pattern match app

---

app.py

Changed the layout of the header so it's more responsive across multiple screen sizes.  Also added a bootstrap logo for branding sake :D

Updated header in app.py

---

examples/colourpicker-histogram.py
pages/colourpicker-histogram.py

This app uses Loading and ColorPicker component to change the bar colour of a histogram.

Created ColorPicker example app

---

examples/parallel-coord-filter.py
pages/parallel-coord-filter.py

This app includes a parallel-coordinates graph that uses the selected coordinates to filter the datatable.

created app with parallel-coordinates to filter a datatable

---

examples/clipboard-csv.py
pages/clipboard-csv.py

This app uses Clipboard component to copy a csv dataset. It also includes Loading component and a scatter plot that has the ability to change the x variable with RadioItems.

created clipboard example app

---

examples/booleanswitch-graph-on-off.py
pages/booleanswitch-graph-on-off.py

This app uses the Boolean Switch component to turn a line chart graph on and off.

created Boolean Switch app to turn a graph on and off

---

examples/booleanswitch-color-by-type.py
pages/booleanswitch-color-by-type.py

This app uses the Boolean Switch component to turn on colour by type for a scatter plot.

created Boolean Switch app to turn on colour by type

---

examples/gauge-scatterplot.py
pages/gauge-scatterplot.py

This app uses Gauge and Slider components to filter values for a scatter plot.

created Gauge app to filter a scatterplot

---

examples/gauge-pie-chart.py
pages/gauge-pie-chart.py

This app uses Gauge and Slider components to filter a pie chart.

created Gauge app to filter values in a pie chart

---

examples/knob-bar-chart.py
pages/knob-bar-chart.py

This app used Knob component to filter values for a bar chart.

created app that uses Knob to filter a bar chart

---

examples/graduated-bar-filter.py
pages/graduated-bar-filter.py

This app uses Graduated Bar and Slider components to filter a bar chart.

created graduated bar example app

---

examples/thermometer-datatable.py
pages/thermometer-datatable.py

This app uses Thermometer and Slider components to filter a DataTable.

create thermometer example app

---

examples/eu-indicators.py

@Coding-with-Adam Here's new commit from a new fork. Please check if this works.

Added eu-indicators via new fork

---

examples/date-picker.py

Example application generates random data when using DatePickerSingle and then filters the data with DatePickerRange.
Created during PYCON sprints with @Coding-with-Adam

added date-picker.py example
